"""make mock_exam_id nullable

Revision ID: 06ca70700e4f
Revises: 5b9f43260c0b
Create Date: 2026-06-08 18:48:15.652750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06ca70700e4f'
down_revision: Union[str, Sequence[str], None] = '5b9f43260c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_answers', 'mock_exam_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_answers', 'mock_exam_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
